export const sampleQAStories = [
  {
    imagePreview: 'https://scontent.cdninstagram.com/v/t51.2885-15/394275499_874922887327967_3887826549847207110_n.jpg?stp=dst-jpg_e35_p360x360&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4xMTcweDIwODAuc2RyIn0&_nc_ht=scontent.cdninstagram.com&_nc_cat=111&_nc_ohc=gzRg9z0WGoQAX8xKW0x&edm=ANmP7GQBAAAA&ccb=7-5&ig_cache_key=MzIxODgzMDI5NDY2MDc4MzU2Nw%3D%3D.2-ccb7-5&oh=00_AfCAfDuUdHc-1Ni9LkhPwqO6rGshyA-e3bzmIj_VWIjFbg&oe=653DEFA3&_nc_sid=982cc7',
    imageShow: 'https://scontent.cdninstagram.com/v/t51.2885-15/394275499_874922887327967_3887826549847207110_n.jpg?se=8&stp=dst-jpg_e35&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4xMTcweDIwODAuc2RyIn0&_nc_ht=scontent.cdninstagram.com&_nc_cat=111&_nc_ohc=gzRg9z0WGoQAX8xKW0x&edm=ANmP7GQBAAAA&ccb=7-5&ig_cache_key=MzIxODgzMDI5NDY2MDc4MzU2Nw%3D%3D.2-ccb7-5&oh=00_AfD3-L-kBomjeC7Ap2zUED7kRfAktqjWXFYs07HCxrPeBA&oe=653DEFA3&_nc_sid=982cc7',
    question: '大家為什麼看/學習人格學+你的MBTI / 九型',
    responders: [
      {
        response: Array(13).fill('日').join(''),
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697990961,
      },
      {
        response: Array(14).fill('日').join(''),
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697990961,
      },
      {
        response: Array(14 * 3).fill('日').join(''),
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697990961,
      },
      {
        response: 'Some very looooooooooooong word in a looooong sentance',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697990961,
      },
      {
        response: Array(66).fill('A').join(''),
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697990961,
      },
      {
        response: '第一行\n第二行',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697990961,
      },
      {
        response: '(INFJ) 希望研究所有人類',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697990961,
      },
      {
        response: '因為覺得MBTI可以解釋到好多自己性格嘅矛盾位 覺得被了解同埋接納 於是好想繼續學落去 + INFJ🕺🏻',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697989711,
      },
      {
        response: '前途迷惘，想知要點行ISTP',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697987792,
      },
      {
        response: 'MBTI是一個很好的模型幫助自己觀察人類✨默默觀察不同mbti間的互動很有趣！（INFP/4w5）',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697986168,
      },
      {
        response: 'Enfp 7w6 因為很喜歡喜歡研究人類 想搞清楚背後動機 ',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697982887,
      },
      {
        response: '有的時候研究人類蠻好玩的/INFP',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697977110,
      },
      {
        response: '被frd推坑的So9',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697976064,
      },
      {
        response: '想了解自己 同想理解其他人點諗野 isfp/5w4 （唔知啱唔啱）',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697971331,
      },
      {
        response: '想快速了解及認識一個人，從而知道如何與那人相處（ISTJ）',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697969837,
      },
      {
        response: '想了解如何type別人、因為能夠type別人令我可以根據他們思考模式與他們相處（ISFJ 6w5)',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697963459,
      },
      {
        response: '比較想知道小編的原因',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697961790,
      },
      {
        response: '知道自己舒服嘅狀態並加以強化',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697955915,
      },
      {
        response: '當初就畢業覺得好迷惘，所以想了解吓自己嘅性格適合做咩工作而玩MBTI🤣 我係ISTP',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697954186,
      },
      {
        response: '想更加了解自己 當然mbti會因為成長或者經歷變咗 所以要運用得宜🥲',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697952252,
      },
      {
        response: '覺得從不同面向了解別人很有趣(ENFP🫢)',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697951432,
      },
      {
        response: '想了解自己和其他人，發現真的能夠更好地與人相處，也能接納理解不同人的想法和行為',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697951206,
      },
      {
        response: '希望更加了解自己係個點既人 ENFJ 8w9 so/sp',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697950822,
      },
      {
        response: '想知道自己係乜。😂',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697950199,
      },
      {
        response: '幾個月前每個人都在ig分享那個mbti帖文（？）但是覺得自己每個都不是 所以開始研究了',
        nickname: 'Nick Name',
        username: 'username',
        profilePicUrl: '/igqa/profile.jpg',
        timestamp: 1697948505,
      },
    ],
    timestamp: 1697933719694204,
  },
];
