name: release

on:
  push:
    branches: ["**"]
    tags: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - id: yarn_cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
        if: steps.yarn_cache.outputs.cache-hit != 'true'
      - run: yarn build
      - run: tar -cvf dist.tar dist
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist.tar,build/ig-helper-linux,build/ig-helper-macos,build/ig-helper-win.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
