name: test

on:
  push:
    branches: ["**"]
    tags: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - build
          - test:acceptance
          # - test:unit
          - test:ui
          - test:type
          - test:lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 5.0.5
        if: matrix.command == 'test:acceptance'
      - id: yarn_cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
        if: steps.yarn_cache.outputs.cache-hit != 'true'
      - run: yarn ${{matrix.command}}
      - uses: actions/upload-artifact@v2
        if: matrix.command == 'build'
        with:
          name: dist
          path: dist

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: tar -cvf dist.tar dist
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist.tar"
          token: ${{ secrets.GITHUB_TOKEN }}
